### ISSUE TITLE
"Sites you've probably visited" incorrectly includes ISP-blocked pages (eg. Pirate Bay)

### ISSUE THREAD

**Issue by DanTup** [diracdeltas/sniffly#10]
Not sure if this is of any interest to you but I just ran this on a Chromebook that I factory reset yesterday. It gave these results (I've removed the dots to avoid linking to some):

- notepad-plus-plus org
- www google com
- www youtube com
- monova org
- ukpirate click
- avxhome se
- ukpirateproxy xyz

The top one I just read an article on; I've definitely visited YT + Google, however I didn't recognise any of the others (they look piracy related and I definitely haven't visited them). Curiously, I tried loading them in my browser (to see what they were) and (for all of them) I got redirected to siteblocked.org with this message:

> Access to this website has been
> Blocked
> Blocking access to ThePiratebay website has been made pursuant to a Court Order dated 27th April 2012 obtained by the members of the BPI (British Recorded Music Industry) Limited.
> 
> www.bpi.co.uk

So, I presume this blocking (which I'll guess is being done by my ISP, TalkTalk in the UK, via DNS) is interfering with your test (and probably in a bad way if anyone was going to infer things using this mechanism!).

**Comment by diracdeltas** [comment]
thanks, i blacklisted those hosts!
