### ISSUE TITLE
Why not send CSP header via php ?

### ISSUE THREAD

**Issue by SleepProgger** [diracdeltas/sniffly#3]
I just wondered, is there a reason you don't send the CSP header via php to be compatible for browsers not supporting the CSP settings via meta tag ?

Something like this should do the work:

```
<?php
$csp_rules = "img-src http://*";
foreach (array("X-WebKit-CSP", "X-Content-Security-Policy", "Content-Security-Policy") as $csp){
    header($csp . ": " . $csp_rules);
}
?>
```

**Comment by diracdeltas** [comment]
I don't write PHP. :)

Happy to accept a pull request to add this to the README as an example though!

**Comment by Qix-** [comment]
As long as it's a response header it shouldn't matter what backend language you use.

---

> I don't write PHP. :)

:+1: This is a good thing.

**Comment by SleepProgger** [comment]
> Happy to accept a pull request to add this to the README

Send.

**Comment by diracdeltas** [comment]
Merged, thanks.
